### ISSUE TITLE
Rename to dag-pb

### ISSUE THREAD

**Issue by daviddias** [ipld/py-ipld-dag#1]
@dhruvbaldawa we have now two ipld/dag formats:

- https://github.com/ipld/js-ipld-dag-pb also known as MerkleDAG
- https://github.com/ipld/js-ipld-dag-cbor a new one that uses any JSON blob and converts to CBOR

Since you are implementing the first, could you rename the module to py-ipld-dag-pb?

**Comment by dhruvbaldawa** [comment]
oh interesting, I was just thinking of implementing a generic DAG and then add separate serialization formats for the same

**Comment by dhruvbaldawa** [comment]
I am actually trying to build a DAG that is not tied to a specific serialization format and can later be extended to any serialization format

**Comment by daviddias** [comment]
~~It won't work.~~ dag-pb requires the Protobuf Schema to be respected (Data + Links) while the dag-cbor can be anything.

**Update:** I mean, feel free to experiment and arrive at your own conclusions, just wanted to make sure you were aware of the differences and why it is this way.

**Comment by dhruvbaldawa** [comment]
Yes, but instead of serializing the data inside the `DAGNode` implementation, if I use a serializer function, which takes the node and returns the serialized representation, it should, in theory, allow me to plug in any serialization format.

or am I missing something here?

**Comment by dhruvbaldawa** [comment]
This is how I was thinking to implement it, I will need to do some more research on how DAGNodes are actually used (and created) and will need some more context on this, to actually check if what I said above does make sense or not.

**Comment by daviddias** [comment]
It is possible to _merge two modules together in the same repo_, but soon you will start having troubles with all the duck typing to fulfill the https://github.com/ipld/interface-ipld-format for both formats in the same module. I believe it to be wiser to have modules that are well scoped and comply with interfaces expected so that they are easier to test and maintain.

**Comment by dhruvbaldawa** [comment]
Ahh yes, I had exactly this in mind. Cool, I will create separate modules for separate serialization formats. I have two more questions

 - Where does the `DAGNode` implementation reside in this case? 
    If there is going to be a common `DAGNode` and `DAGLink` implementation to be shared across 
   multiple formats, I'd rather keep it over here and have separate `dag-pb`, `dag-cbor` packages. 
 - Will the `DAGNode` implementation be same for `eth-*` interface implementations as it is for `dag-pb` and `dag-cbor`?

Too many questions I am sorry, just trying to understand how it _actually_ works :)

**Comment by daviddias** [comment]
An IPLD Format implementation in JavaScript must expose an interface that matches the one defined in [interface-ipld-format spec](https://github.com/ipld/interface-ipld-format). For languages that we haven't specified yet, the important is not the name of the functions or the organization, the important part is keeping the _purity of what an IPLD Format is_ which is described by:

- Has a resolver interface that given an object/block of that format, we can retrieve a value from a valid path
- Has utilities for serialization and deserialization.
- It is modular enough so that an [IPLD Resolver Service](https://github.com/ipld/js-ipld-resolver) can [pick multiple formats and resolve through all of them](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L59-L98).

Watch this ["Enter the Merkle Forest"](https://www.youtube.com/watch?v=Bqs_LzBjQyk) talk, it explains really well the motivation behind these interfaces and pluggability. 

> Too many questions I am sorry, just trying to understand how it actually works :)

No problem at all! It helps me understand where things are less clear so that I can improve docs too :) Keep them coming!

**Comment by dhruvbaldawa** [comment]
Cool, now I get the bigger picture. 

But I am still confused that once the serialization and resolution and all this stuff is finished and you get to a `DAGNode`, is the `DAGNode` and `DAGLink` implementation something that is shared across all these IPLD formats? or can these formats have their own `DAGNode` and `DAGLink` implementations?

**Comment by rvagg** [comment]
closing for archival
