### ISSUE TITLE
Why are there so many special methods and other underscored members in the dag.py file?

### ISSUE THREAD

**Issue by drozdziak1** [ipld/py-ipld-dag#5]
Does using `self.__class__` and co. really help performance?

**Comment by dhruvbaldawa** [comment]
No, it does not help in performance. I followed this answer: https://stackoverflow.com/a/15774013/972283

**Comment by drozdziak1** [comment]
Do we have any deepcopy needs yet, or is this for some future immutable content stuff?

**Comment by dhruvbaldawa** [comment]
Yes, we need it when content changes for a child node. In which case the parent node has to be updated. We are storing data in a dictionary which is a mutable data structure and hence could possibly lead to issues.

**Comment by rvagg** [comment]
closing for archival
