### ISSUE TITLE
Calls

### ISSUE THREAD

**Issue by drozdziak1** [ipld/py-ipld-dag#7]
## Overview
This issue is part of an experiment to give some sort of project management backbone to our efforts. It will focus on figuring out the details for calls regarding the `py-ipld-dag` project. **All feedback is welcome and appreciated.** 

## Rationale
* As of today, the specs for IPFS and IPLD can be a bit tricky to understand or (in some cases) hard to come by
* Architectural software design challenges and ideas are usually easier to follow when shown live on a diagram

## Timezones
Currently we're in the UTC+1 - UTC+5:30 range

## Other stuff
* **Google Hangouts** worked the best so far for hosting the calls
* It might be nice to figure out a way to pool talking points for each call so that we're confident about each agenda

## Gitter channel
https://gitter.im/ipfs-ipld/Lobby

**Comment by drozdziak1** [comment]
# Call planning \#2 
## Time windows a.k.a. when's everyone (usually) available
* @drozdziak1: 2:30PM UTC - 8:00PM UTC, Monday - Friday,
## Getting added above
Comment this issue and mention me to get your time/weekday preference noted above

**Comment by glyif** [comment]
@drozdziak1 when is the next call?

**Comment by drozdziak1** [comment]
@glyif we've somewhat slowed down  lately mainly due to the specs being rather inconclusive. Don't know the status for today, but I'm sure things will get more lively once the specs become more coherent

**Comment by rvagg** [comment]
closing for archival
